# Generated by Django 5.2.4 on 2025-08-31 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_email_remove_student_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='file_report',
            field=models.FileField(null=True, upload_to='files/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(null=True, upload_to='images/%y/%m/%d'),
        ),
    ]
